name = "ClosedWaveguideDispersion"
uuid = "d74d092a-a0c6-412f-a98c-c8383163d778"
authors = ["jyzhang <peakfind@126.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
